name: Hearthstone
version: '${project.version}'
main: io.github.thesowut.hearthstone.handler.Hearthstone
api-version: 1.19
authors: [ TheSowut ]
description: Teleport with style
commands:
  get:
    description: Get a hearthstone
    usage: /<command>
    permission: hearthstone.get
    permission-message: You do not have permission.
  sethome:
    description: Set hearthstone home
    usage: /<command>
    permission: hearthstone.sethome
    permission-message: You do not have permission.
  reload:
    description: Reload the plugin
    usage: /<command>
    permission: hearthstone.reload
    permission-message: You do not have permission.
